# Generated by Django 4.2 on 2023-04-16 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('data', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('brand', models.TextField()),
                ('price', models.IntegerField()),
                ('quanity', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
